# Base image with Python and system dependencies
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    curl

# Copy requirements.txt
COPY requirements.txt .

# Install Python packages
RUN pip install -r requirements.txt

# Set default working directory (optional)
WORKDIR /app
