# version ??

services:

  app:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile

    # image: rag_service_app:latest
    image: ragservice-app:latest
    container_name: ragservice-app
    ports: # dont use it since we are using nginx
     - "127.0.0.1:8000:8000" 
    expose: # documents the port for other containers (optional, mostly for clarity)
      - "8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL} 
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      # - SEP_TERMINAL_ID=${SEP_TERMINAL_ID}
      # - SEP_PAYMENT_URL=${SEP_PAYMENT_URL}
      # - SEP_VERIFY_URL=${SEP_VERIFY_URL}
      # - SEP_REVERSE_URL=${SEP_REVERSE_URL}
      # - PAYMENT_CALLBACK_URL=${PAYMENT_CALLBACK_URL}
      # - FRONTEND_PAYMENT_RESULT_URL=${FRONTEND_PAYMENT_RESULT_URL}
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./docs:/app/docs
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      # - /etc/ssl/private/api-key.pem:/app/certs/api-key.pem:ro # No need to mount SSL certs here anymore if nginx handles SSL
      # - /etc/ssl/certs/api-cert.pem:/app/certs/api-cert.pem:ro # No need to mount SSL certs here anymore if nginx handles SSL

    command:
      - sh
      - -c
      - >
          alembic upgrade head &&
          exec gunicorn app.main:app
          --worker-class uvicorn.workers.UvicornWorker
          --workers 1
          --bind 0.0.0.0:8000
          --worker-connections 500
          --timeout 30
          --keep-alive 2
          --log-level info
          --access-logfile -

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy

    env_file:
      - .env
    restart: unless-stopped
    networks:
      - rag_network
    deploy: # 🔴 VPS is cpu only
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # MySQL Database
  mysql:
    image: mysql:8.0.39 #🔴 hardcoded !
    # image: mysql:5.7.42 #🔴 hardcoded !
    container_name: ragservice_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"  # Dev only, not reachable from internet
    expose: # documents the port for other containers (optional, mostly for clarity)
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    # network_mode: "host"
    networks:
      - rag_network

  # Redis
  redis:
    image: valkey/valkey:8 #🔴 hardcoded !
    container_name: ragservice_redis
    ports:
      - "127.0.0.1:6379:6379" # Dev only, not reachable from internet
    expose: # documents the port for other containers (optional, mostly for clarity)
      - "6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --save 60 1000
      --save 300 10
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    # network_mode: "host"
    restart: unless-stopped
    networks:
      - rag_network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3 #🔴 hardcoded !
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0 #🔴 hardcoded !
    container_name: ragservice_elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-ragflow_test}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "127.0.0.1:9200:9200"  # Dev only, not reachable from internet
    #   - "9300:9300" #🔴 hardcoded !
    expose:  # documents the port for other containers (optional, mostly for clarity)
      - "9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:${ELASTICSEARCH_PASSWORD:-ragflow_test} http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    # network_mode: "host"  
    restart: unless-stopped
    networks:
      - rag_network
  
  
  nginx:
    image: nginx:alpine
    container_name: ragservice_nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx_with_front.conf:/etc/nginx/conf.d/default.conf:ro
      ## If you want SSL terminated at nginx:
      # - /etc/ssl/certs/api-cert.pem:/etc/nginx/certs/api-cert.pem:ro
      # - /etc/ssl/private/api-key.pem:/etc/nginx/certs/api-key.pem:ro
    depends_on:
      app:
        condition: service_healthy
      # frontend:                       
      #   condition: service_started
    restart: unless-stopped
    networks:
      - rag_network


volumes:
  mysql_data: 
  redis_data: 
  elasticsearch_data: 

networks:
  rag_network:
    driver: bridge