limit_req_zone $server_name zone=global_limit:10m rate=10r/s; # how many request get processed per sec

upstream fastapi_backend {
    # server 127.0.0.1:8000;
    server app:8000;
    keepalive 32;
}

# # Redirect HTTP → HTTPS # uncomment it for https
# server {
#     listen 80;
#     server_name _;
#     return 301 https://$host$request_uri;
# }

server {
    # listen 443 ssl;  # uncomment it for https
    listen 80;
    server_name _;

    # ssl_certificate     /etc/nginx/certs/api-cert.pem; # uncomment it for https
    # ssl_certificate_key /etc/nginx/certs/api-key.pem; # uncomment it for https

    # ssl_protocols TLSv1.2 TLSv1.3; # uncomment it for https
    # ssl_ciphers HIGH:!aNULL:!MD5; # uncomment it for https
    # ssl_prefer_server_ciphers on; # uncomment it for https
    # ssl_session_cache shared:SSL:10m; # uncomment it for https

    # add_header X-Frame-Options DENY;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always; # uncomment it for https
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    client_max_body_size 10M;

    gzip on;
    gzip_types application/json text/plain application/javascript;
    gzip_min_length 1000;

    location / {
        limit_req zone=global_limit burst=200; # how to many are allowed to be held in queue - extera will be refused
        limit_req_status 429; 

        proxy_pass http://fastapi_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        
        proxy_connect_timeout 20s;
        proxy_read_timeout 180s; # the time that user kept waiting for his responce
        proxy_send_timeout 40s; # the time that user is held in queue to send his request
        proxy_set_header Connection "";
    }

    location /nginx-health {
        access_log off;
        return 200 "ok";
    }
}

# sudo cp nginx.conf /etc/nginx/conf.d/fastapi.conf