"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77f7a32ba333'
down_revision = '4078008a858e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # Fill NULLs before making columns NOT NULL
    op.execute("UPDATE users SET email = CONCAT(username, '@placeholder.local') WHERE email IS NULL")
    op.execute("UPDATE users SET username = CONCAT('user_', LEFT(id, 8)) WHERE username IS NULL")
    op.alter_column('users', 'email', existing_type=sa.String(255), nullable=False)
    op.alter_column('users', 'username', existing_type=sa.String(50), nullable=False)