"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855538473aa6'
down_revision = '20260406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discount_usages_ibfk_1', 'discount_usages', type_='foreignkey')
    op.drop_constraint('discount_usages_ibfk_3', 'discount_usages', type_='foreignkey')
    op.create_foreign_key(None, 'discount_usages', 'discount_codes', ['discount_code_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discount_usages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'discount_usages', type_='foreignkey')
    op.drop_constraint(None, 'discount_usages', type_='foreignkey')
    op.create_foreign_key('discount_usages_ibfk_3', 'discount_usages', 'users', ['user_id'], ['id'])
    op.create_foreign_key('discount_usages_ibfk_1', 'discount_usages', 'discount_codes', ['discount_code_id'], ['id'])
    # ### end Alembic commands ###


