"""data ingestion pipeline added

Revision ID: e58990d3da3e
Revises: 855538473aa6
Create Date: 2026-05-02

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58990d3da3e'
down_revision = '855538473aa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), server_default='local', nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'REVIEW', 'INDEXING', 'READY', 'FAILED', name='documentstatus'), server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=16), nullable=True),
    sa.Column('parser_used', sa.String(length=64), nullable=True),
    sa.Column('ocr_used', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom', sa.JSON(), nullable=True),
    sa.Column('ingestion_version', sa.String(length=16), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_documents_content_hash'), 'ingestion_documents', ['content_hash'], unique=True)
    op.create_index(op.f('ix_ingestion_documents_status'), 'ingestion_documents', ['status'], unique=False)
    op.create_table('ingestion_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('page_range', sa.JSON(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('section_title', sa.String(length=512), nullable=True),
    sa.Column('section_path', sa.JSON(), nullable=True),
    sa.Column('heading_level', sa.Integer(), nullable=True),
    sa.Column('element_type', sa.String(length=32), server_default='text', nullable=False),
    sa.Column('is_footnote', sa.Boolean(), nullable=False),
    sa.Column('is_table', sa.Boolean(), nullable=False),
    sa.Column('table_markdown', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('script_direction', sa.String(length=4), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(length=128), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('edited_by_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['ingestion_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_chunks_doc_approved', 'ingestion_chunks', ['doc_id', 'approved'], unique=False)
    op.create_index(op.f('ix_ingestion_chunks_doc_id'), 'ingestion_chunks', ['doc_id'], unique=False)
    op.create_index('ix_ingestion_chunks_doc_index', 'ingestion_chunks', ['doc_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_ingestion_chunks_vector_id'), 'ingestion_chunks', ['vector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop child table first so MySQL drops its FK + indexes automatically.
    op.drop_table('ingestion_chunks')

    # Then drop parent table.
    op.drop_table('ingestion_documents')
